name: release Windows

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: false
        type: string
  push:
    branches:
      - master
      - mod-latest

env:
  OutputArch: "windows-64"
  OutputPath:  "${{ github.workspace }}/v2rayN/Release"

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2
      with:
        submodules: 'recursive'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore and Build v2rayN
      run: |
        msbuild v2rayN/v2rayN/v2rayN.csproj /p:Configuration=Release /p:Platform="Any CPU" /t:Restore /p:OutputPath="${{ env.OutputPath }}/v2rayN"
        msbuild v2rayN/v2rayN/v2rayN.csproj /p:Configuration=Release /p:Platform="Any CPU" /t:Build /p:OutputPath="${{ env.OutputPath }}/v2rayN"

    - name: Restore and Build AmazTool
      run: |
        msbuild v2rayN/AmazTool/AmazTool.csproj /p:Configuration=Release /p:Platform="Any CPU" /t:Restore /p:OutputPath="${{ env.OutputPath }}/AmazTool"
        msbuild v2rayN/AmazTool/AmazTool.csproj /p:Configuration=Release /p:Platform="Any CPU" /t:Build /p:OutputPath="${{ env.OutputPath }}/AmazTool"
   
    - name: Upload build artifacts
      uses: actions/upload-artifact@v6.0.0
      with:
        name: v2rayN-windows
        path: |
          ${{ env.OutputPath }}/**
    
    # release zip archive
    - name: Package release zip archive
      if: github.event.inputs.release_tag != ''
      run: |
        powershell -Command "Compress-Archive -Path '${{ env.OutputPath }}/*' -DestinationPath 'v2rayN-windows.zip' -Force"
    
    - name: Upload zip archive to release
      uses: svenstaro/upload-release-action@v2
      if: github.event.inputs.release_tag != ''
      with:
        file: v2rayN-windows.zip
        tag: ${{ github.event.inputs.release_tag }}
        file_glob: true
        prerelease: true
